In [197]:
import pandas as pd

In [198]:
pd.__version__

'2.2.2'

In [199]:
exam_data = pd.read_csv("exams.csv", quotechar='"')
exam_data

# The data appears to be out of 100, but it is possible that the range of scores is different, therefore possibly making them not directly comparable
# This makes standardization essential

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,male,group E,associate's degree,standard,completed,79,75,81
1,female,group C,associate's degree,free/reduced,none,56,65,64
2,male,group D,bachelor's degree,standard,none,86,68,74
3,female,group A,bachelor's degree,standard,none,68,78,76
4,female,group D,high school,free/reduced,none,49,68,61
...,...,...,...,...,...,...,...,...
95,female,group A,master's degree,free/reduced,completed,59,76,80
96,female,group D,high school,free/reduced,none,60,62,61
97,female,group C,some college,standard,none,69,82,83
98,male,group D,some high school,standard,none,89,83,79
99,female,group A,master's degree,free/reduced,completed,65,88,88

In [200]:
math_average = exam_data['math score'].mean()
reading_average = exam_data['reading score'].mean()
writing_average = exam_data['writing score'].mean()

print('Math Avg: ', math_average)
print('Reading Avg: ', reading_average)
print('Writing Avg: ', writing_average)

Math Avg:  65.06
Reading Avg:  67.28
Writing Avg:  66.47

In [201]:
# Skikit-learn offers a very useful toolkit called preprocessing, which can be used to standardize a dataset
# The SCALE function will divide all the data points, for example the math scores by the average and subtract the standard deviation

from sklearn import preprocessing

exam_data[['math score']] = preprocessing.scale(exam_data[['math score']])
exam_data[['reading score']] = preprocessing.scale(exam_data[['reading score']])
exam_data[['writing score']] = preprocessing.scale(exam_data[['writing score']])

# To check the updated dataset with standardized numbers
exam_data

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,male,group E,associate's degree,standard,completed,0.994557,0.574138,1.049901
1,female,group C,associate's degree,free/reduced,none,-0.646391,-0.169564,-0.178476
2,male,group D,bachelor's degree,standard,none,1.493976,0.053547,0.544099
3,female,group A,bachelor's degree,standard,none,0.209756,0.797248,0.688613
4,female,group D,high school,free/reduced,none,-1.145810,0.053547,-0.395248
...,...,...,...,...,...,...,...,...
95,female,group A,master's degree,free/reduced,completed,-0.432354,0.648508,0.977643
96,female,group D,high school,free/reduced,none,-0.361008,-0.392675,-0.395248
97,female,group C,some college,standard,none,0.281101,1.094729,1.194416
98,male,group D,some high school,standard,none,1.708013,1.169099,0.905386
99,female,group A,master's degree,free/reduced,completed,-0.004281,1.540950,1.555703

In [202]:
math_average = exam_data['math score'].mean()
reading_average = exam_data['reading score'].mean()
writing_average = exam_data['writing score'].mean()

print('Math Avg: ', math_average)
print('Reading Avg: ', reading_average)
print('Writing Avg: ', writing_average)

# Checking the averages of these columns again. The averages are very close or equal to zero because the mean and stdev have been subtracted
# After scaling, the mean is zero (or almost zero) and the stdev of the scores is one

Math Avg:  -1.5693175925424186e-16
Reading Avg:  -1.0880185641326534e-16
Writing Avg:  8.881784197001253e-17

In [203]:
# A very useful library function that scikit-learn offers is the label encoder
# It is used when there are meaningful comparisions between the categorical variables e.g. low<medium<high
# Only meaningful to the developer, not the machine learning model

le = preprocessing.LabelEncoder()
exam_data['gender'] = le.fit_transform(exam_data['gender'].astype(str)) 
# the fit_transform method will go through all the categorical values in the gender column and transform them into numbers. The numerical values for
# gender will be assigned to the gender column in the pandas data frame

In [204]:
exam_data.head() # this column is now made up of #'s (male = 1, female = 0)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,1,group E,associate's degree,standard,completed,0.994557,0.574138,1.049901
1,0,group C,associate's degree,free/reduced,none,-0.646391,-0.169564,-0.178476
2,1,group D,bachelor's degree,standard,none,1.493976,0.053547,0.544099
3,0,group A,bachelor's degree,standard,none,0.209756,0.797248,0.688613
4,0,group D,high school,free/reduced,none,-1.145810,0.053547,-0.395248

In [205]:
le.classes_ # will give the unique values of gender that the column holds

array(['female', 'male'], dtype=object)

In [206]:
pd.get_dummies(exam_data['race/ethnicity'], dtype='int') # allows to represent any categorical value in its one-hot form

    group A  group B  group C  group D  group E
0         0        0        0        0        1
1         0        0        1        0        0
2         0        0        0        1        0
3         1        0        0        0        0
4         0        0        0        1        0
..      ...      ...      ...      ...      ...
95        1        0        0        0        0
96        0        0        0        1        0
97        0        0        1        0        0
98        0        0        0        1        0
99        1        0        0        0        0

[100 rows x 5 columns]

In [207]:
exam_data = pd.get_dummies(exam_data, columns=['race/ethnicity'], dtype='int')
# Assigning the one-hot encoding to be part of the tabular data in the exam_data data frame

In [208]:
exam_data

,gender,parental level of education,lunch,test preparation course,math score,reading score,writing score,race/ethnicity_group A,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E
0,1,associate's degree,standard,completed,0.994557,0.574138,1.049901,0,0,0,0,1
1,0,associate's degree,free/reduced,none,-0.646391,-0.169564,-0.178476,0,0,1,0,0
2,1,bachelor's degree,standard,none,1.493976,0.053547,0.544099,0,0,0,1,0
3,0,bachelor's degree,standard,none,0.209756,0.797248,0.688613,1,0,0,0,0
4,0,high school,free/reduced,none,-1.145810,0.053547,-0.395248,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,master's degree,free/reduced,completed,-0.432354,0.648508,0.977643,1,0,0,0,0
96,0,high school,free/reduced,none,-0.361008,-0.392675,-0.395248,0,0,0,1,0
97,0,some college,standard,none,0.281101,1.094729,1.194416,0,0,1,0,0
98,1,some high school,standard,none,1.708013,1.169099,0.905386,0,0,0,1,0
99,0,master's degree,free/reduced,completed,-0.004281,1.540950,1.555703,1,0,0,0,0

In [209]:
exam_data = pd.get_dummies(exam_data, columns=['parental level of education', 'lunch', 'test preparation course'], dtype='int') 
# can work on multiple columns at once

In [210]:
exam_data.head()

,gender,math score,reading score,writing score,race/ethnicity_group A,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,parental level of education_associate's degree,parental level of education_bachelor's degree,parental level of education_high school,parental level of education_master's degree,parental level of education_some college,parental level of education_some high school,lunch_free/reduced,lunch_standard,test preparation course_completed,test preparation course_none
0,1,0.994557,0.574138,1.049901,0,0,0,0,1,1,0,0,0,0,0,0,1,1,0
1,0,-0.646391,-0.169564,-0.178476,0,0,1,0,0,1,0,0,0,0,0,1,0,0,1
2,1,1.493976,0.053547,0.544099,0,0,0,1,0,0,1,0,0,0,0,0,1,0,1
3,0,0.209756,0.797248,0.688613,1,0,0,0,0,0,1,0,0,0,0,0,1,0,1
4,0,-1.145810,0.053547,-0.395248,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1