In [287]:
# Basic frequency-based representation of words in documents
from sklearn.feature_extraction.text import CountVectorizer

In [288]:
# The corpus has 4 documents
corpus = ['This is the first document.','This is the second document.','Third document. Document number three','Number four. To repeat, number four']

In [289]:
# initialize
vectorizer = CountVectorizer()
# generating a bag of words in a numeric form
bag_of_words = vectorizer.fit_transform(corpus)

bag_of_words

<4x12 sparse matrix of type '<class 'numpy.int64'>'
	with 18 stored elements in Compressed Sparse Row format>

In [290]:
print(bag_of_words) # format = (documentID, wordID)
# There are 4 documents in the input corpus, and therefore, every document is given a unique ID from 0 to 3, as the first coordinate in the points
# Every word in the document corpus is also given a unique individual ID
# The second coordinates in the first 5 points represent the first 5 words in document 1, and so on
# Both word frequencies and integer representations are found within this dataset

# An example of word frequency is the number 2 in the second column for the point (3,2), as the 4th document has the word 'four' repeat twice

# An example of integer representations includes the fact that because both the first and second documents contain all the same words except one, where
# the first doc says 'first' doc while the second doc says 'second' doc. This is represented down below, as otherwise the rest of the first 10 points
# are identical

  (0, 9)	1
  (0, 3)	1
  (0, 7)	1
  (0, 1)	1
  (0, 0)	1
  (1, 9)	1
  (1, 3)	1
  (1, 7)	1
  (1, 0)	1
  (1, 6)	1
  (2, 0)	2
  (2, 8)	1
  (2, 4)	1
  (2, 10)	1
  (3, 4)	2
  (3, 2)	2
  (3, 11)	1
  (3, 5)	1

In [291]:
# In order to access the ID that corresponds to a particular word. In this case, the word 'document' corresponds to the number 0
vectorizer.vocabulary_.get('document')

# Typically the most frequently used words are assigned lower IDs

0

In [292]:
vectorizer.vocabulary_ # in order to access all the IDs

{'this': 9,
 'is': 3,
 'the': 7,
 'first': 1,
 'document': 0,
 'second': 6,
 'third': 8,
 'number': 4,
 'three': 10,
 'four': 2,
 'to': 11,
 'repeat': 5}

In [293]:
import pandas as pd

pd.__version__

'2.2.2'

In [294]:
# To understand the set up of these words in a tabular format

pd.DataFrame(bag_of_words.toarray(), columns=vectorizer.get_feature_names_out()) 

# rows are the individual documents, columns are the words in the vocab
# the numbers in the cells of the table represent the frequency of individual words in each doc

,document,first,four,is,number,repeat,second,the,third,this,three,to
0,1,1,0,1,0,0,0,1,0,1,0,0
1,1,0,0,1,0,0,1,1,0,1,0,0
2,2,0,0,0,1,0,0,0,1,0,1,0
3,0,0,2,0,2,1,0,0,0,0,0,1

In [295]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer() # associates scores with every word in the document corpus
bag_of_words = vectorizer.fit_transform(corpus)

In [296]:
print(bag_of_words) # all the document ID word ID combinations are associated with a score as seen below

  (0, 0)	0.3528554929793508
  (0, 1)	0.5528163151092931
  (0, 7)	0.43584673254990375
  (0, 3)	0.43584673254990375
  (0, 9)	0.43584673254990375
  (1, 6)	0.5528163151092931
  (1, 0)	0.3528554929793508
  (1, 7)	0.43584673254990375
  (1, 3)	0.43584673254990375
  (1, 9)	0.43584673254990375
  (2, 10)	0.4850008395708102
  (2, 4)	0.3823802326982809
  (2, 8)	0.4850008395708102
  (2, 0)	0.6191395067937654
  (3, 5)	0.3432724906138499
  (3, 11)	0.3432724906138499
  (3, 2)	0.6865449812276998
  (3, 4)	0.5412799489419371

In [297]:
vectorizer.vocabulary_.get('document')

0

In [298]:
pd.DataFrame(bag_of_words.toarray(), columns=vectorizer.get_feature_names_out())

,document,first,four,is,number,repeat,second,the,third,this,three,to
0,0.352855,0.552816,0.000000,0.435847,0.00000,0.000000,0.000000,0.435847,0.000000,0.435847,0.000000,0.000000
1,0.352855,0.000000,0.000000,0.435847,0.00000,0.000000,0.552816,0.435847,0.000000,0.435847,0.000000,0.000000
2,0.619140,0.000000,0.000000,0.000000,0.38238,0.000000,0.000000,0.000000,0.485001,0.000000,0.485001,0.000000
3,0.000000,0.000000,0.686545,0.000000,0.54128,0.343272,0.000000,0.000000,0.000000,0.000000,0.000000,0.343272

In [299]:
vectorizer.vocabulary_

{'this': 9,
 'is': 3,
 'the': 7,
 'first': 1,
 'document': 0,
 'second': 6,
 'third': 8,
 'number': 4,
 'three': 10,
 'four': 2,
 'to': 11,
 'repeat': 5}

In [300]:
from sklearn.feature_extraction.text import HashingVectorizer

vectorizer = HashingVectorizer(n_features=8) # use Hashing instead of Count if there is a large vocabulary amount of words
# The use of hashing buckets to represent words allows to scale large data sets; n_features is the input argument for the number of hash buckets
feature_vector = vectorizer.fit_transform(corpus)
print(feature_vector)

# Word IDs are from 0-7 (the second coordinates of the points), as there are 8 buckets
# Due to the size of the vocab being larger than the # of buckets, as it should be, multiple words can hash to the same bucket
# A disadvantage of HashingVectorizer is that there is no way to get back to the original word from its hash bucket value
# The frequencies of each token is not represented in raw # form, as this is some kind of a normalized form

  (0, 0)	-0.8944271909999159
  (0, 5)	0.4472135954999579
  (0, 6)	0.0
  (1, 0)	-0.5773502691896258
  (1, 3)	0.5773502691896258
  (1, 5)	0.5773502691896258
  (1, 6)	0.0
  (2, 0)	-0.7559289460184544
  (2, 3)	0.3779644730092272
  (2, 5)	0.3779644730092272
  (2, 7)	0.3779644730092272
  (3, 0)	0.31622776601683794
  (3, 3)	0.31622776601683794
  (3, 5)	0.6324555320336759
  (3, 7)	0.6324555320336759